title: dev.ac.uk
twitter: devacuk
github: devacuk
name: dev.ac.uk
description: We make stuff. Supported by UCISA and Jisc.
url: https://devacuk.github.io
permalink: pretty
paginate: 15
theme: jekyll-theme-minimal
google_analytics: UA-107703046-1
